### ISSUE TITLE
Why the *** is it a promise??

### ISSUE THREAD

**Issue by marcofugaro** [YeasterEgg/voronoi-creator#1]
Everything has async/await because of the `getCostFunction`, but the `getCostFunction` itself has no promises, so why is it async??

https://github.com/YeasterEgg/voronoi-creator/blob/cb34575720116a80a8e033495c592f8616d4b403/utils.ts#L74-L89

**Comment by YeasterEgg** [comment]
the current gradient descent implementation is written so that the cost function can be both sync or async, and the sync version is wrapped in a Promise.
even if the optimization step will be changed in the future, using different algorithms, probably they will be implemented to accept the cost function in the same way
